# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        # define your own name of filter
        20x20:
            filters:
                thumbnail:
                    size:          [20, 20]
                    mode:          outbound
                    allow_upscale: true
        45x45:
            filters:
                thumbnail:
                    size:          [45, 45]
                    mode:          outbound
                    allow_upscale: true
        50x50:
            filters:
                thumbnail:
                    size:          [50, 50]
                    mode:          outbound
                    allow_upscale: true
        300x300:
            filters:
                thumbnail:
                    size:          [300, 300]
                    mode:          outbound
                    allow_upscale: true
        600x375:
            filters:
                thumbnail:
                    size:          [600, 375]
                    mode:          outbound
                    allow_upscale: true
        1000x600:
            filters:
                thumbnail:
                    size:          [1000, 600]
                    mode:          outbound
                    allow_upscale: true
