twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        facebook_url:  'https://www.facebook.com/thomas.kanzig'
        instagram_url: 'https://www.instagram.com/thomas.kanzig/'
        github_url:    'https://github.com/thomaskanzig'
        linkedin_url:  'https://www.linkedin.com/in/thomas-kanzig-b1018a116/'
        name_site:     'Thomas Kanzig'
