twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        facebook_url:  '%env(FACEBOOK_URL)%'
        instagram_url: '%env(INSTAGRAM_URL)%'
        github_url:    '%env(GITHUB_URL)%'
        linkedin_url:  '%env(LINKEDIN_URL)%'
        name_site:     '%env(APP_NAME)%'
